default:
  image: docker:20
  services:
    - name: docker:20-dind

stages:
  - build
  - push_image
  - tests
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
  GIT_DEPTH: "5"

build_python:
  stage: build
  image: python:3.9
  tags:
    - docker
  before_script:
    - python --version
  script:
    - pip install -r python/requirements.txt
  artifacts:
    when: always
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - ./*
    exclude:
      - ./git/
      - ./git/**/*
      - .gitlab-ci.yml
      - .gitignore

build_docker_image:
  stage: build
  needs: [build_python]
  tags:
    - docker
  before_script: 
    - docker info
  script:
    - echo "build docker image"
    - docker build -t $CI_REGISTRY_IMAGE:latest ./python/

push_docker_image:
  stage: push_image
  needs: [build_docker_image]
  tags:
    - docker
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker push $CI_REGISTRY_IMAGE:latest



# build_minio:
# stage: build
# image: minio/minio:latest
# tags:
#   - docker
# script:
#   - pip install -r python/requirements.txt
# artifacts:
#   when: always
#   name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
#   paths:
#     - ./*
#   exclude:
#     - ./git/**/*
#     - .gitlab-ci.yml
#     - .gitignore
# only:
#   - main