build:
  stage: build
  tags:
    - docker
  script:
    - docker build -t dimaaasex911/python-flask:latest
    - docker image push dimaaasex911/python-flask:latest
    - aws ecs update-service --cluster python-flask --service python-flask-service --force-new-deployment
  only:
    - main
    - try_gitlab_ci
  
  