image: docker

services:
  - docker:dind

before_script:
  - docker info
  - docker-compose --version

stages:
  - "test"
  - "build"

test:
  stage: test
  tags:
    - "docker"
  script:
    - pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml

build:
  stage: build
  tags:
    - "docker"
  script:
    - apk add --no-cache docker-compose
    - docker-compose down
    - docker-compose up -d
  only:
    - main
  
  