image: python:3.9

stages:
  - ver
  - build
  - tests
  - deploy

ver:
  stage: ver
  tags:
    - docker
  script:
    - python --version
    - whoami

build_job:
  stage: build
  tags:
    - docker
  script:
    - pip install -r python/requirements.txt
  artifacts:
    when: always
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - ./*
    exclude:
      - ./git/**/*
      - .gitlab-ci.yml
      - .gitignore
  only:
    - main
    - try_gitlab_ci
  
  