stages:
  - build
  - push_image
  - tests
  - deploy

build_python:
  stage: build
  image: python:3.9
  tags:
    - docker
  before_script:
    - python --version
  script:
    - pip install -r python/requirements.txt
  artifacts:
    when: always
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - ./*
    exclude:
      - ./git/
      - ./git/**/*
      - .gitlab-ci.yml
      - .gitignore

build_docker_image:
  stage: build
  needs: [build_python]
  tags:
    - docker
  before_script: 
    - docker info
  script:
    #- cd python
    - docker build -t dimaaasex911/python-flask ./Python




# build_minio:
# stage: build
# image: minio/minio:latest
# tags:
#   - docker
# script:
#   - pip install -r python/requirements.txt
# artifacts:
#   when: always
#   name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
#   paths:
#     - ./*
#   exclude:
#     - ./git/**/*
#     - .gitlab-ci.yml
#     - .gitignore
# only:
#   - main