version: '3.7'
services:
  minio:
    image: 'minio/minio:latest'
    container_name: minio
    command: 'server --console-address ":9001" /data/'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: dima
      MINIO_ROOT_PASSWORD: mypassword
      MINIO_ACCESS_KEY: dima
      MINIO_SECRET_KEY: mypassword
    volumes:
      - 'minio-storage:/data'
    networks:
      - my-network
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:9000/minio/health/live'
      interval: 30s
      timeout: 20s
      retries: 3
  mc:
    image: minio/mc
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: dima
      MINIO_ROOT_PASSWORD: mypassword
    entrypoint: >
      /bin/sh -c "curl --retry 3 --retry-connrefused --retry-delay 2
      http://minio:9000 && /usr/bin/mc config host add srv http://minio:9000
      $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD} && /usr/bin/mc mb srv/images
      && /usr/bin/mc policy set public srv/images"
    networks:
      - my-network
  traefik:
    image: 'traefik:v2.5'
    container_name: traefik
    command:
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    networks:
      - my-network
  python:
    build:
      context: ./python
    container_name: python
    labels:
      - traefik.enable=true
      - traefik.http.routers.python.rule=Host(`localhost`)
      - traefik.http.routers.python.entrypoints=web
    ports:
      - '5000:5000'
    depends_on:
      - minio
    restart: on-failure
    volumes:
      - './python:/python'
    networks:
      - my-network
    # lets try app.py  
    #command: python main.py
    command: python /usr/local/lib/app/app.py
    environment:
      MINIO: 'minio:9000'
      MINIO_PREFIX: 'http://localhost:9001/images'
      MINIO_ROOT_USER: dima
      MINIO_ROOT_PASSWORD: mypassword
volumes:
  minio-storage: null
networks:
  my-network:
    driver: bridge
