
## Redis
redis:

  metrics:
    # -- Deploy metrics service and redis-exporter sidecar
    enabled: true
    
  serviceMonitor:
    # -- Enable a prometheus ServiceMonitor
    enabled: false

## Server
server:
 
  ## Server metrics service configuration
  metrics:
    # -- Deploy metrics service
    enabled: true
    
  serviceMonitor:
    # -- Enable a prometheus ServiceMonitor
    enabled: false

  ingress:
    enabled: true
    hosts:
     - argocd.myownserv.space
  config: 
    url: https://argocd.myownserv.space
  extraArgs: 
    - --insecure
 
configs:
  secret:
    argocdServerAdminPassword: "$2a$10$JoA4nXs6hcl9lqSaX0Na0eBHChFk86U7AJkLujyKUFqCir3FSxH3a"
    argocdServerAdminPasswordMtime: "2006-01-02T15:04:05Z"