apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-credentials
  namespace: kube-system
type: Opaque
stringData:
  email: dimaaasex911@gmail.com
  apiKey: 336047f5a887c30d64f6584804af3c13c21f4
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: kube-system
data:
  traefik-config.yaml: |
    http:
      middlewares:
        headers-default:
          headers:
            sslRedirect: true
            browserXssFilter: true
            contentTypeNosniff: true
            forceSTSHeader: true
            stsIncludeSubdomains: true
            stsPreload: true
            stsSeconds: 15552000
            customFrameOptionsValue: SAMEORIGIN