---
# Main playbook for install LEMP on Linux
- name: Provision LEMP and related tools
  hosts: ubuntu_servers
  become: true
  gather_facts: yes

  roles:
     - nginx
     - php
     - mysql
     - restartsvcs